### ISSUE TITLE
New Package Request: Crash

### ISSUE THREAD

**Issue by Veritasosrb** [coreos/fedora-coreos-tracker#1238]
Please try to answer the following questions about the package you are requesting:

1. What, if any, are the additional dependencies on the package? (i.e. does it pull in Python, Perl, etc)
“Crash” is majorly written in C and does not need Python, Perl etc.
Crash needs kernel-debuginfo rpm for debug vmlinux and debug ko modules.

2. What is the size of the package and its dependencies?
Crash rpm size is ~8.5MB
Size of kernel-debuginfo rpm is ~500MB

3. What problem are you trying to solve with this package? Or what functionality does the package provide?
“Crash” is useful to live debug a kernel issue. This is useful when triaging issues in device drivers and kernel components.
Many a times in k8s environment, for a kernel component issue, dump of the system cannot be taken and debugged later as it may result in downtime for other applications running on the cluster. 

4. Can the software provided by the package be run from a container?  Explain why or why not.
No. We need to debug issues related to kernel modules which could be connected to through system calls from any container. Eg: Storage drivers can be connected through read/write system calls by the applications running inside the containers. “Crash” utility should be invoked from the host to inspect kernel threads and data structures. 

5. Can the tool(s) provided by the package be helpful in debugging container runtime issues?
Yes

6. Can the tool(s) provided by the package be helpful in debugging networking issues?
Yes. Network stack within kernel modules/drivers can be debugged through “Crash” utility.

7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.
This should be possible. Expectation would be that layering should not require rebooting the system. Also, the image maintenance and distribution after layering should not be required by the end user. A very simple user interface similar to configuration through Machine Config Operator would be desirable. 
“Crash” will be required on cloud k8s distributions also and hence layering should be made simple similar to extension configuration Eg: usbguard through MCO

8. In the case of packages providing services and binaries, can the packaging be adjusted to just deliver binaries?
Crash rpm contains single important binary /usr/bin/crash. Crash rpm does not deliver other Services.
Kernel-debuginfo rpms contain binaries and debug ko modules. 

9. Can the tool(s) provided by the package be used to do things we’d rather users not be able to do in FCOS? (e.g. can it be abused as a Turing complete interpreter?)
No.

10. Does the software provided by the package have a history of CVEs?
No.

**Comment by travier** [comment]
> 4. Can the software provided by the package be run from a container?  Explain why or why not.
>    No. We need to debug issues related to kernel modules which could be connected to through system calls from any container. Eg: Storage drivers can be connected through read/write system calls by the applications running inside the containers. “Crash” utility should be invoked from the host to inspect kernel threads and data structures.

- You should be able to run the `crash` tool from a privileged container as those have access to everything on the host and other containers.
- Due to the size of the kernel debuginfo packages, it is extremely unlikely that this will ever be included in the image.

> 7. Is it possible to layer the package onto the base OS as a day 2 operation?  Explain why or why not.
>    This should be possible. Expectation would be that layering should not require rebooting the system. Also, the image maintenance and distribution after layering should not be required by the end user. A very simple user interface similar to configuration through Machine Config Operator would be desirable.
>    “Crash” will be required on cloud k8s distributions also and hence layering should be made simple similar to extension configuration Eg: usbguard through MCO

- You can use `rpm-ostree install --apply-live pkgname` to install a package live for the current deployment (and the next one).
- If you want to have the MCO then you probably want OKD 🙂.

**Comment by Veritasosrb** [comment]
When running crash from a privileged container, it dumped core. Here is the stack trace:
Program terminated with signal 11, Segmentation fault.
#0  0x0000559ad36f7d9e in sort_context_array ()
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.7.el6.x86_64 libgcc-4.4.7-3.3.el6_4.x86_64 zlib-1.2.3-25.el6.x86_64
(gdb) bt
#0  0x0000559ad36f7d9e in sort_context_array ()
#1  0x0000559ad370abc5 in task_init ()
#2  0x0000559ad36908d3 in main_loop ()
#3  0x0000559ad3912067 in ?? ()
#4  0x0000559ad3910ada in catch_errors ()
#5  0x0000559ad39131b6 in ?? ()
#6  0x0000559ad3910ada in catch_errors ()
#7  0x0000559ad3913534 in gdb_main_entry ()
#8  0x0000559ad368ee04 in main ()
(gdb) q
Do we know if this is a known issue with Crash when run from a privileged container? crash-7.3.1-5.el8.x86_64 is being used.

**Comment by travier** [comment]
This is probably best reported upstream in the Fedora Bugzilla
