### ISSUE TITLE
kola: `Cannot allocate memory` when running `osmet-pack`

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#1294]
We've seen this off and on in the pipeline/CI for a while now. Usually a re-run will succeed.

It's happened enough now that we should investigate the root cause.

```
[2022-09-09T17:41:30.605Z] + chroot /sysroot/ostree/deploy/fedora-coreos/deploy/41df20a1fccf7a2463089628bdbcf0677818eb965f9868f77e153775f2969e41.0 coreos-installer pack osmet /dev/disk/by-id/virtio-osmet --description 'Fedora CoreOS 36.20220909.dev.0' --checksum 6b3ed3f6af4160658ea56adb93108c558a99a2fc409456f00dd9ea88c8f623be --output /tmp/osmet.bin --fast
[2022-09-09T17:41:30.605Z] Total OSTree objects scanned from /root: 11577 (11572 mapped, 5 empty)
[2022-09-09T17:41:30.605Z] Total OSTree objects found in /boot: 2
[2022-09-09T17:41:30.605Z] Duplicate extents dropped: 0
[2022-09-09T17:41:30.605Z] Overlapping extents clamped: 0
[2022-09-09T17:41:30.605Z] Total /root extents: 11572
[2022-09-09T17:41:30.605Z] Duplicate extents dropped: 0
[2022-09-09T17:41:30.605Z] Overlapping extents clamped: 0
[2022-09-09T17:41:30.605Z] Total /boot extents: 6
[2022-09-09T17:41:30.605Z] Packing image
[2022-09-09T17:41:42.756Z] Total bytes skipped: 1274825728
[2022-09-09T17:41:42.757Z] Total bytes written: 997438464
[2022-09-09T17:41:42.757Z] Total bytes written (compressed): 3868208
[2022-09-09T17:41:42.757Z] Verifying that repacked image matches digest
[2022-09-09T17:41:47.987Z] Packing successful!
[2022-09-09T17:41:48.241Z] + mv /tmp/osmet.bin /srv/tmp/tmp-osmet-pack/osmet.bin
[2022-09-09T17:41:48.242Z] mv: failed to access '/srv/tmp/tmp-osmet-pack/osmet.bin': Cannot allocate memory
[2022-09-09T17:41:48.496Z] 2022-09-09 17:41:48,279 ERROR - Command returned bad exitcode
[2022-09-09T17:41:48.496Z] 2022-09-09 17:41:48,280 ERROR - COMMAND: ['/usr/lib/coreos-assembler/osmet-pack', 'builds/36.20220909.dev.0/s390x/fedora-coreos-36.20220909.dev.0-metal.s390x.raw', '512', '/srv/tmp/buildpost-live/initrd-rootfs/fedora-coreos-36.20220909.dev.0-metal.s390x.raw.osmet', '6b3ed3f6af4160658ea56adb93108c558a99a2fc409456f00dd9ea88c8f623be', 'fast']
[2022-09-09T17:41:48.497Z] Traceback (most recent call last):
[2022-09-09T17:41:48.497Z]   File "/usr/lib/coreos-assembler/cmd-buildextend-live", line 715, in <module>
[2022-09-09T17:41:48.497Z]     generate_iso()
[2022-09-09T17:41:48.497Z]   File "/usr/lib/coreos-assembler/cmd-buildextend-live", line 303, in generate_iso
[2022-09-09T17:41:48.497Z]     runcmd(['/usr/lib/coreos-assembler/osmet-pack',
[2022-09-09T17:41:48.497Z]   File "/usr/lib/coreos-assembler/cosalib/cmdlib.py", line 78, in runcmd
[2022-09-09T17:41:48.497Z]     raise e
[2022-09-09T17:41:48.497Z]   File "/usr/lib/coreos-assembler/cosalib/cmdlib.py", line 70, in runcmd
[2022-09-09T17:41:48.497Z]     cp = subprocess.run(cmd, **pargs)
[2022-09-09T17:41:48.497Z]   File "/usr/lib64/python3.10/subprocess.py", line 524, in run
[2022-09-09T17:41:48.497Z]     raise CalledProcessError(retcode, process.args,
[2022-09-09T17:41:48.497Z] subprocess.CalledProcessError: Command '['/usr/lib/coreos-assembler/osmet-pack', 'builds/36.20220909.dev.0/s390x/fedora-coreos-36.20220909.dev.0-metal.s390x.raw', '512', '/srv/tmp/buildpost-live/initrd-rootfs/fedora-coreos-36.20220909.dev.0-metal.s390x.raw.osmet', '6b3ed3f6af4160658ea56adb93108c558a99a2fc409456f00dd9ea88c8f623be', 'fast']' returned non-zero exit status 1.
```

This particular failure happened in [bump-lockfile#62](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/62/pipeline).

**Comment by cgwalters** [comment]
Pretty sure this is just 9p getting worse and we need to do https://github.com/coreos/coreos-assembler/issues/1812

**Comment by dustymabe** [comment]
Do you know we can push forward https://github.com/coreos/coreos-assembler/issues/1812#issuecomment-1144958381 ?

**Comment by dustymabe** [comment]
Saw this for x86_64 (runs in pipeline, not on multi-arch builder) in [bump-lockfile#68](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/68/pipeline/574).

**Comment by dustymabe** [comment]
Saw this for s390x in [bump-lockfile#76](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/76/pipeline/523).

**Comment by dustymabe** [comment]
Saw this for s390x in [bump-lockfile#85](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/85/pipeline/528).

**Comment by dustymabe** [comment]
Saw this for s390x in [bump-lockfile#88](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/88/pipeline/520)

**Comment by dustymabe** [comment]
Saw this for s390x in [bump-lockfile#99](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/99/pipeline/608)

**Comment by dustymabe** [comment]
Saw this for s390x in [bump-lockfile#120](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/120/pipeline/588)

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-assembler/pull/3011 does a bunch of work in that area. It cleans up a bunch of things but I'm not sure if it'll help this specific case or not. Still probably better to get it in before digging more into this I think.

**Comment by dustymabe** [comment]
Seen on `s390x` in [bump-lockfile#175](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/blue/organizations/jenkins/bump-lockfile/detail/bump-lockfile/175/pipeline/520).

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-assembler/pull/3011 has now merged. Let's see if it helps with this. Otherwise, there's an atomic option we can do here which is to transfer the osmet file over virtio-serial instead.

**Comment by dustymabe** [comment]
Thanks @jlebon - I'll close this out and re-open if we see it again.

**Comment by jlebon** [comment]
We're still hitting this, currently at least on aarch64.
