### ISSUE TITLE
cosa buildextend-hashlist-experimental fails in branched stream

### ISSUE THREAD

**Issue by aaradhak** [coreos/fedora-coreos-tracker#1429]
### Describe the bug

The issue was observed in the fedora-coreos pipeline build [924](https://jenkins-fedora-coreos-pipeline.apps.ocp.fedoraproject.org/job/build/924/). The command `cosa buildextend-hashlist-experimental` failed to execute on the [branched][x86_64] build.

### Reproduction steps

This issue couldnt be reproduced locally. 
Tried to execute the cosa buildextend-hashlist-experimental on the branched stream, the command seems to execute when tried locally.

### Expected behavior

```
aaradhak@fedora ~/fcos $ cosa buildextend-hashlist-experimental
COREOS_ASSEMBLER_CONFIG_GIT=/var/home/aaradhak/coderepo/fedora-coreos-config
+ podman run --rm -ti --security-opt label=disable --privileged --uidmap=1000:0:1 --uidmap=0:1:1000 --uidmap 1001:1001:64536 -v /var/home/aaradhak/fcos:/srv/ --device /dev/kvm --device /dev/fuse --tmpfs /tmp -v /var/tmp:/var/tmp --name cosa -v /var/home/aaradhak/coderepo/fedora-coreos-config:/srv/src/config/:ro quay.io/coreos-assembler/coreos-assembler:latest buildextend-hashlist-experimental
Hash list created at builds/38.20230221.dev.0/x86_64/exp-hash.json
+ rc=0
+ set +x
```

### Actual behavior

```
[2023-02-21T20:42:15.517Z] + cosa buildextend-hashlist-experimental
[2023-02-21T20:44:36.836Z] find: ���tmp/repo/tmp/keylime-checkout/usr/etc/credstore���: Permission denied
[2023-02-21T20:44:36.836Z] find: ���tmp/repo/tmp/keylime-checkout/usr/etc/credstore.encrypted���: Permission denied
[2023-02-21T20:44:36.836Z] Traceback (most recent call last):
[2023-02-21T20:44:36.836Z]   File "/usr/lib/coreos-assembler/cmd-buildextend-hashlist-experimental", line 195, in <module>
[2023-02-21T20:44:36.836Z]     main()
[2023-02-21T20:44:36.836Z]   File "/usr/lib/coreos-assembler/cmd-buildextend-hashlist-experimental", line 187, in main
[2023-02-21T20:44:36.836Z]     hashlist.populate_hash_list()
[2023-02-21T20:44:36.836Z]   File "/usr/lib/coreos-assembler/cmd-buildextend-hashlist-experimental", line 96, in populate_hash_list
[2023-02-21T20:44:36.836Z]     subprocess.check_call(['find', checkout, '-type', 'd', '-exec',
[2023-02-21T20:44:36.836Z]   File "/usr/lib64/python3.11/subprocess.py", line 413, in check_call
[2023-02-21T20:44:36.836Z]     raise CalledProcessError(retcode, cmd)
[2023-02-21T20:44:36.836Z] subprocess.CalledProcessError: Command '['find', 'tmp/repo/tmp/keylime-checkout', '-type', 'd', '-exec', 'chmod', 'u+w', '{}', '+']' returned non-zero exit status 1.
[2023-02-21T20:44:36.836Z] error: failed to execute cmd-buildextend-hashlist-experimental: exit status 1
script returned exit code 1
```

### System details

[branched][x86_64] 38.20230221.92.0

**Comment by dustymabe** [comment]
This is now also failing in `rawhide` after https://github.com/coreos/fedora-coreos-config/pull/2258. It appears the new systemd package is bringing in some files that cause us to get a permission issue here.

**Comment by dustymabe** [comment]
workaround while we investigate: https://github.com/coreos/fedora-coreos-pipeline/pull/819

**Comment by aaradhak** [comment]
I came across this point in systemd [NEWS ](https://github.com/systemd/systemd/blob/41aca66ba4f3a72ad709ef27e334392ef177450c/NEWS#L565-L568)for changes with systemd-253. I am wondering if this is something related to the permission issue which we are observing in this issue.

`Default tmpfiles.d/ configuration will now automatically create credentials storage directory '/etc/credstore/' with the appropriate, secure permissions. If '/run/credstore/' exists, its permissions will be fixed too in case they are not correct.`

**Comment by jlebon** [comment]
Likely, yes. Sounds like that new dir doesn't even have rx access for the owner. It would be less efficient, but would probably work to replace the `+` with a `;` in that `find` invocation and `u+w` with `u+rwx`.

**Comment by dustymabe** [comment]
> probably work to replace the `+` with a `;` in that `find` invocation and `u+w` with `u+rwx`.

for my own education, can you expand on why doing those two things will fix the problem?

**Comment by jlebon** [comment]
> > probably work to replace the `+` with a `;` in that `find` invocation and `u+w` with `u+rwx`.
> 
> for my own education, can you expand on why doing those two things will fix the problem?

The initial reason for the `chmod` was that we were unable to delete files on exit ([coreos/coreos-assembler@`d16d78f` (#3142)](https://github.com/coreos/coreos-assembler/pull/3142/commits/d16d78f304c4c04bff0083829c02d6fb0ce15f81). I haven't tested this, but I think the problem here is very likely that `find` can't recurse into `/etc/credstore`.  So we add `x` so that it can recurse into it. With `+`, `find` accumulates paths and runs `chmod` once (or batched by the arg limit I guess). But for this, we need it to `chmod` the dir before it tries to recurse into it, so we change to `;`.

Anyway, I think this too should probably be part of `ostree checkout`, e.g. `--readable-dirs` or something.
