### ISSUE TITLE
rawhide: failing in ostree signing stage in the pipline

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-tracker#909]
I believe the [change to OCI formatted tarball for rawhide](https://github.com/coreos/fedora-coreos-config/pull/1097) maybe broke some assumptions here:

```
Waiting for a response to the sent request
Verifying OSTree signature
Valid signature from Fedora <fedora-35-primary@fedoraproject.org> (787EA6AE1147EEE56C40B30CDB4639719867C58F)
error: Importing oci-archive:builds/35.20210726.91.0/x86_64/fedora-coreos-35.20210726.91.0-ostree.x86_64.ociarchive: Fetching manifest: skopeo inspect failed
time="2021-07-26T05:04:35Z" level=fatal msg="Error parsing image name \"oci-archive:builds/35.20210726.91.0/x86_64/fedora-coreos-35.20210726.91.0-ostree.x86_64.ociarchive\": error creating temp directory: error untarring file \"/var/tmp/oci198489804\": chown /var/tmp/oci198489804/objects/51: operation not permitted"
Traceback (most recent call last):
  File "/usr/lib/coreos-assembler/cmd-sign", line 277, in <module>
    sys.exit(main())
  File "/usr/lib/coreos-assembler/cmd-sign", line 42, in main
    args.func(args)
  File "/usr/lib/coreos-assembler/cmd-sign", line 97, in cmd_robosignatory
    robosign_ostree(args, s3, build, gpgkey)
  File "/usr/lib/coreos-assembler/cmd-sign", line 198, in robosign_ostree
    import_ostree_commit('tmp/repo', builddir, build, force=True)
  File "/usr/lib/coreos-assembler/cosalib/cmdlib.py", line 272, in import_ostree_commit
    subprocess.check_call(['rpm-ostree', 'ex-container', 'import', '--repo', tmpd,
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rpm-ostree', 'ex-container', 'import', '--repo', '/tmp/tmp5w7o3hj5', '--write-ref', '35.20210726.91.0', 'oci-archive:builds/35.20210726.91.0/x86_64/fedora-coreos-35.20210726.91.0-ostree.x86_64.ociarchive']' returned non-zero exit status 1.
script returned exit code 1
```

https://jenkins-fedora-coreos.apps.ocp.ci.centos.org/blue/organizations/jenkins/fedora-coreos%2Ffedora-coreos-fedora-coreos-pipeline/detail/fedora-coreos-fedora-coreos-pipeline/2261/pipeline

**Comment by cgwalters** [comment]
OK that's not an easy fix, let's back this out for now https://github.com/coreos/fedora-coreos-config/pull/1137

I think we may benefit from native support in ostree-rs-ext for this.

**Comment by cgwalters** [comment]
This is fixed right?

**Comment by jlebon** [comment]
Yup indeed!
